apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: link
spec:
  version: {{ .TagName }}
  homepage: https://github.com/umutbasal/kubectl-link
  shortDescription: Access cluster resources without vpn
  description: |
    kubectl-link simplifies accessing your Kubernetes
    pods and services by automatically creating port-forwards on demand
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/umutbasal/kubectl-link/releases/download/{{ .TagName }}/kubectl-link_Darwin_x86_64.tar.gz" .TagName }}
    bin: kubectl-link
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/umutbasal/kubectl-link/releases/download/{{ .TagName }}/kubectl-link_Darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-link